# Generated by Django 2.2.6 on 2019-10-31 14:03

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('c_parent', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='lmlappadmin.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('logo', models.ImageField(blank=True, max_length=200, null=True, upload_to='employerlogo')),
                ('company_name', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('company_motto', models.CharField(max_length=100)),
                ('brief_details', models.TextField()),
                ('bizness_entity_type', models.CharField(max_length=100)),
                ('date_created', models.DateField(default=datetime.datetime(2019, 10, 31, 17, 2, 59, 942989))),
                ('description', models.TextField()),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('company_email', models.CharField(max_length=100)),
                ('kra_number', models.CharField(max_length=100)),
                ('bussiness_reg_no', models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=200)),
                ('category', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Category')),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(max_length=200, upload_to='customerImages')),
                ('country', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('skils', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('personel_reg_no', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField(default=datetime.datetime(2019, 10, 31, 17, 2, 59, 937531))),
                ('landmark', models.CharField(max_length=100)),
                ('huduma_no', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(max_length=200)),
                ('disability', models.TextField()),
                ('marital_status', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_licence', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biography', models.TextField()),
                ('category', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Category')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('READ', 'Read'), ('TRASH', 'Trash'), ('UNREAD', 'Unread')], default='UNREAD', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='social_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_url', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('referee', models.CharField(max_length=100)),
                ('referee_phonenumber', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Customer')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Query')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('comapny_email', models.CharField(max_length=200)),
                ('company_phone', models.CharField(max_length=200)),
                ('position_held', models.CharField(max_length=200)),
                ('date_from', models.DateField(default=datetime.datetime(2019, 10, 31, 17, 2, 59, 939712))),
                ('date_to', models.DateField(default=datetime.datetime(2019, 10, 31, 17, 2, 59, 939712))),
                ('experience', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paid_to', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_date', models.DateField(default=datetime.datetime(2019, 10, 31, 17, 2, 59, 950555))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Customer')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paid_to', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_date', models.DateField(default=datetime.datetime(2019, 10, 31, 17, 2, 59, 949558))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('googlr_plus', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRegistrationPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Company')),
            ],
        ),
    ]
