# Generated by Django 2.1.15 on 2019-12-31 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmlappadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rank_status',
            field=models.CharField(choices=[('PREMIUM', 'Premium'), ('PLATINUM', 'Platinum'), ('PRO_BASIC', 'Pro_basic'), ('PRO_ULTIMATE', 'Pro_ultimate'), ('ULTIMATE', 'Ultimate'), ('BASIC', 'Basic'), ('UNDEFINED', 'Undefined')], default='UNDEFINED', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('DEACTIVATED', 'Deactivated'), ('REGISTERED_CONFIRMED', 'Registerd_confirmed')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rank_status',
            field=models.CharField(choices=[('PREMIUM', 'Premium'), ('BASIC', 'Basic'), ('ULTIMATE', 'Ultimate')], default='BASIC', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('DEACTIVATED', 'Deactivated'), ('REGISTERED_CONFIRMED', 'Registerd_confirmed')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 16, 26, 18, 24085)),
        ),
    ]
