# Generated by Django 2.1.11 on 2019-11-14 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmlappadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 11, 15, 21, 298658)),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('REGISTERED_CONFIRMED', 'Registerd_confirmed'), ('PREMIUM', 'Premium'), ('DEACTIVATED', 'Deactivated')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 11, 15, 21, 291661)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('REGISTERED_CONFIRMED', 'Registerd_confirmed'), ('PREMIUM', 'Premium'), ('DEACTIVATED', 'Deactivated')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='customerpayments',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 11, 15, 21, 305654)),
        ),
        migrations.AlterField(
            model_name='employerpayments',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 11, 15, 21, 306653)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 11, 15, 21, 295659)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 11, 15, 21, 295659)),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('TRASH', 'Trash'), ('READ', 'Read'), ('UNREAD', 'Unread')], default='UNREAD', max_length=100),
        ),
    ]
