# Generated by Django 2.2.6 on 2019-10-31 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmlappadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 17, 50, 20, 770100)),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('PREMIUM', 'Premium'), ('REGISTERED_CONFIRMED', 'Registerd_confirmed')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 17, 50, 20, 769102)),
        ),
        migrations.AlterField(
            model_name='customerpayments',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 17, 50, 20, 776895)),
        ),
        migrations.AlterField(
            model_name='employerpayments',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 17, 50, 20, 776895)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 17, 50, 20, 770100)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 17, 50, 20, 770100)),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('UNREAD', 'Unread'), ('TRASH', 'Trash'), ('READ', 'Read')], default='UNREAD', max_length=100),
        ),
    ]
