# Generated by Django 2.1.7 on 2019-11-13 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmlappadmin', '0002_auto_20191114_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 2, 9, 30, 472044)),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('REGISTERED_CONFIRMED', 'Registerd_confirmed'), ('NEWBIE', 'Newbie'), ('PREMIUM', 'Premium'), ('DEACTIVATED', 'Deactivated')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 2, 9, 30, 457760)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('REGISTERED_CONFIRMED', 'Registerd_confirmed'), ('NEWBIE', 'Newbie'), ('PREMIUM', 'Premium'), ('DEACTIVATED', 'Deactivated')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='customerpayments',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 2, 9, 30, 491029)),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 2, 9, 30, 462368)),
        ),
        migrations.AlterField(
            model_name='employerpayments',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 2, 9, 30, 492207)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 2, 9, 30, 462368)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 2, 9, 30, 462368)),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('TRASH', 'Trash'), ('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD', max_length=100),
        ),
    ]
