# Generated by Django 2.1.15 on 2020-01-01 17:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmlappadmin', '0002_auto_20191231_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactusemployee',
            name='company',
        ),
        migrations.AddField(
            model_name='contactusemployee',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='rank_status',
            field=models.CharField(choices=[('UNDEFINED', 'Undefined'), ('PRO_BASIC', 'Pro_basic'), ('ULTIMATE', 'Ultimate'), ('PREMIUM', 'Premium'), ('PLATINUM', 'Platinum'), ('PRO_ULTIMATE', 'Pro_ultimate'), ('BASIC', 'Basic')], default='UNDEFINED', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('DEACTIVATED', 'Deactivated'), ('NEWBIE', 'Newbie'), ('REGISTERED_CONFIRMED', 'Registerd_confirmed')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyregistrationpayment',
            name='payment_status',
            field=models.CharField(choices=[('UNPAYED', 'Unpayed'), ('PAYED', 'Payed')], default='UNPAYED', max_length=200),
        ),
        migrations.AlterField(
            model_name='companystatuspayment',
            name='payment_status',
            field=models.CharField(choices=[('UNPAYED', 'Unpayed'), ('PAYED', 'Payed')], default='UNPAYED', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rank_status',
            field=models.CharField(choices=[('ULTIMATE', 'Ultimate'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium')], default='BASIC', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('DEACTIVATED', 'Deactivated'), ('NEWBIE', 'Newbie'), ('REGISTERED_CONFIRMED', 'Registerd_confirmed')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='customerpayments',
            name='payment_status',
            field=models.CharField(choices=[('UNPAYED', 'Unpayed'), ('PAYED', 'Payed')], default='UNPAYED', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 20, 25, 55, 57315)),
        ),
    ]
