# Generated by Django 2.1.7 on 2019-11-14 09:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmlappadmin', '0003_auto_20191114_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_county', models.CharField(max_length=200)),
                ('Ward', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 12, 35, 43, 759681)),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('REGISTERED_CONFIRMED', 'Registerd_confirmed'), ('PREMIUM', 'Premium'), ('DEACTIVATED', 'Deactivated'), ('NEWBIE', 'Newbie')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='county',
            name='county_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 12, 35, 43, 741866)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('REGISTERED_CONFIRMED', 'Registerd_confirmed'), ('PREMIUM', 'Premium'), ('DEACTIVATED', 'Deactivated'), ('NEWBIE', 'Newbie')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='customerpayments',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 12, 35, 43, 774363)),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 12, 35, 43, 746823)),
        ),
        migrations.AlterField(
            model_name='employerpayments',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 12, 35, 43, 776788)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 12, 35, 43, 748854)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 12, 35, 43, 748854)),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('READ', 'Read'), ('UNREAD', 'Unread'), ('TRASH', 'Trash')], default='UNREAD', max_length=100),
        ),
        migrations.AddField(
            model_name='sub_county',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.County'),
        ),
    ]
