# Generated by Django 2.1.7 on 2019-11-14 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmlappadmin', '0004_auto_20191114_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_county',
            name='county',
        ),
        migrations.AddField(
            model_name='sub_county',
            name='county_no',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 14, 9, 49, 458881)),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('REGISTERED_CONFIRMED', 'Registerd_confirmed'), ('PREMIUM', 'Premium'), ('NEWBIE', 'Newbie'), ('DEACTIVATED', 'Deactivated')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 14, 9, 49, 442013)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('REGISTERED_CONFIRMED', 'Registerd_confirmed'), ('PREMIUM', 'Premium'), ('NEWBIE', 'Newbie'), ('DEACTIVATED', 'Deactivated')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='customerpayments',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 14, 9, 49, 483318)),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 14, 9, 49, 450124)),
        ),
        migrations.AlterField(
            model_name='employerpayments',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 14, 9, 49, 483318)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 14, 9, 49, 450124)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 14, 9, 49, 450124)),
        ),
    ]
