# Generated by Django 2.1.7 on 2019-11-14 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmlappadmin', '0005_auto_20191114_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_County',
        ),
        migrations.AlterField(
            model_name='company',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 14, 33, 11, 439741)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 14, 33, 11, 435181)),
        ),
        migrations.AlterField(
            model_name='customerpayments',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 14, 33, 11, 449144)),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 14, 33, 11, 438190)),
        ),
        migrations.AlterField(
            model_name='employerpayments',
            name='paid_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 14, 33, 11, 450144)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 14, 33, 11, 438190)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2019, 11, 14, 14, 33, 11, 438190)),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('TRASH', 'Trash'), ('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD', max_length=100),
        ),
    ]
