# Generated by Django 2.1.11 on 2019-11-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmlappadmin', '0006_auto_20191114_1433'),
        ('lmlappadmin', '0002_auto_20191114_1115'),
    ]

    operations = [
    ]
