# Generated by Django 2.1.11 on 2019-11-17 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmlappadmin', '0008_auto_20191118_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rank_status',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PRO_ULTIMATE', 'Pro_ultimate'), ('ULTIMATE', 'Ultimate'), ('UNDEFINED', 'Undefined'), ('PLATINUM', 'Platinum'), ('PREMIUM', 'Premium'), ('PRO_BASIC', 'Pro_basic')], default='UNDEFINED', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('DEACTIVATED', 'Deactivated'), ('REGISTERED_CONFIRMED', 'Registerd_confirmed')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('NEWBIE', 'Newbie'), ('DEACTIVATED', 'Deactivated'), ('REGISTERED_CONFIRMED', 'Registerd_confirmed'), ('PREMIUM', 'Premium')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 2, 44, 23, 936621)),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('TRASH', 'Trash')], default='UNREAD', max_length=100),
        ),
    ]
