# Generated by Django 2.1.11 on 2019-11-18 20:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmlappadmin', '0009_auto_20191118_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPricingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStatusPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipt_no', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('payment_status', models.CharField(choices=[('PAYED', 'Payed'), ('UNPAYED', 'Unpayed')], default='UNPAYED', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerpayments',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='customerpayments',
            name='paid_to',
        ),
        migrations.AddField(
            model_name='companyregistrationpayment',
            name='payment_status',
            field=models.CharField(choices=[('PAYED', 'Payed'), ('UNPAYED', 'Unpayed')], default='UNPAYED', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='rank_status',
            field=models.CharField(choices=[('ORDINARY', 'Ordinary'), ('PREMIUM', 'Premium'), ('ULTIMATE', 'Ultimate')], default='UNDEFINED', max_length=200),
        ),
        migrations.AddField(
            model_name='customerpayments',
            name='payment_status',
            field=models.CharField(choices=[('PAYED', 'Payed'), ('UNPAYED', 'Unpayed')], default='UNPAYED', max_length=200),
        ),
        migrations.AddField(
            model_name='customerpayments',
            name='recipt_no',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='rank_status',
            field=models.CharField(choices=[('PREMIUM', 'Premium'), ('BASIC', 'Basic'), ('ULTIMATE', 'Ultimate'), ('UNDEFINED', 'Undefined'), ('PRO_BASIC', 'Pro_basic'), ('PRO_ULTIMATE', 'Pro_ultimate'), ('PLATINUM', 'Platinum')], default='UNDEFINED', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('DEACTIVATED', 'Deactivated'), ('NEWBIE', 'Newbie'), ('REGISTERED_CONFIRMED', 'Registerd_confirmed')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('DEACTIVATED', 'Deactivated'), ('NEWBIE', 'Newbie'), ('REGISTERED_CONFIRMED', 'Registerd_confirmed')], default='NEWBIE', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 23, 0, 17, 7933)),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('READ', 'Read'), ('UNREAD', 'Unread'), ('TRASH', 'Trash')], default='UNREAD', max_length=100),
        ),
        migrations.AddField(
            model_name='companystatuspayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmlappadmin.Company'),
        ),
    ]
